[pytest]
pythonpath = .
testpaths = tests

[coverage:run]
omit = 
    */tests/*
    */migrations/*
    */__pycache__/*

[coverage:report]
# Set fail_under to 70% for CI/CD pipeline
fail_under = 70
precision = 0
skip_covered = False
skip_empty = True
