from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum

class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

@dataclass
class SecurityContext:
    """
    Represents the market context for a specific security at a point in time.
    """
    ticker: str
    date: datetime
    # Pricing Data
    price: float
    indicators: Dict[str, float] = field(default_factory=dict) # e.g. {"RSI": 50.0}
    # Metadata
    news_headlines: List[str] = field(default_factory=list)
    financials: Dict[str, float] = field(default_factory=dict)

    def to_json(self) -> str:
        import json
        return json.dumps({
            "ticker": self.ticker,
            "date": self.date.isoformat(),
            "price": self.price,
            "indicators": self.indicators,
            "news": self.news_headlines,
            "financials": self.financials
        }, ensure_ascii=False)

@dataclass
class AgentSignal:
    """
    Represents a trading signal generated by an agent.
    """
    agent_name: str
    ticker: str
    signal: SignalType
    confidence: float
    reasoning: str
    timestamp: datetime = field(default_factory=datetime.now)

@dataclass
class FeedbackExample:
    """
    Represents a feedback loop example: Context -> Response -> Outcome.
    """
    id: Optional[str]
    agent_name: str
    context: SecurityContext
    response_text: str
    signal: SignalType
    outcome_score: float # -1.0 to 1.0
    timestamp: datetime = field(default_factory=datetime.now)

@dataclass
class Position:
    ticker: str
    quantity: float
    average_cost: float
    current_price: float = 0.0
    
    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price
    
    @property
    def unrealized_pnl(self) -> float:
        return (self.current_price - self.average_cost) * self.quantity

@dataclass
class Portfolio:
    user_id: str
    cash_balance: float
    positions: Dict[str, Position] = field(default_factory=dict)
    
    @property
    def total_market_value(self) -> float:
        return sum(p.market_value for p in self.positions.values())
        
    @property
    def net_liquidation_value(self) -> float:
        return self.cash_balance + self.total_market_value

@dataclass
class AnalysisReport:
    id: str
    user_id: str
    date: datetime
    content: str
    summary: str
    signals: List[AgentSignal] = field(default_factory=list)
