from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum

class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

@dataclass
class SecurityContext:
    """
    Represents the market context for a specific security at a point in time.
    """
    ticker: str
    date: datetime
    # Pricing Data
    price: float
    indicators: Dict[str, float] = field(default_factory=dict) # e.g. {"RSI": 50.0}
    # Metadata
    news_headlines: List[str] = field(default_factory=list)
    financials: Dict[str, float] = field(default_factory=dict)

    def to_json(self) -> str:
        import json
        return json.dumps({
            "ticker": self.ticker,
            "date": self.date.isoformat(),
            "price": self.price,
            "indicators": self.indicators,
            "news": self.news_headlines,
            "financials": self.financials
        }, ensure_ascii=False)

@dataclass
class AgentSignal:
    """
    Represents a trading signal generated by an agent.
    """
    agent_name: str
    ticker: str
    signal: SignalType
    confidence: float
    reasoning: str
    timestamp: datetime = field(default_factory=datetime.now)

@dataclass
class FeedbackExample:
    """
    Represents a feedback loop example: Context -> Response -> Outcome.
    """
    id: Optional[str]
    agent_name: str
    context: SecurityContext
    response_text: str
    signal: SignalType
    outcome_score: float # -1.0 to 1.0
    timestamp: datetime = field(default_factory=datetime.now)

@dataclass
class Position:
    ticker: str
    quantity: float
    average_cost: float
    current_price: float = 0.0
    
    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price
    
    @property
    def unrealized_pnl(self) -> float:
        return (self.current_price - self.average_cost) * self.quantity

@dataclass
class Portfolio:
    user_id: str
    cash_balance: float
    positions: Dict[str, Position] = field(default_factory=dict)
    
    @property
    def total_market_value(self) -> float:
        return sum(p.market_value for p in self.positions.values())
        
    @property
    def net_liquidation_value(self) -> float:
        return self.cash_balance + self.total_market_value

@dataclass
class AnalysisReport:
    id: str
    user_id: str
    date: datetime
    content: str
    summary: str
    signals: List[AgentSignal] = field(default_factory=list)


class RiskCategory(Enum):
    """Categories of risk keywords. 風險關鍵字類別。"""
    LEGAL = "legal"              # 法律風險 (lawsuit, SEC, fraud)
    FINANCIAL = "financial"      # 財務風險 (bankruptcy, default, downgrade)
    OPERATIONAL = "operational"  # 營運風險 (recall, data breach, layoff)
    GEOPOLITICAL = "geopolitical"  # 地緣政治 (war, sanctions, tariff)
    MARKET = "market"            # 市場風險 (crash, margin call, bubble)
    CUSTOM = "custom"            # 使用者自訂


@dataclass
class RiskKeyword:
    """
    A weighted risk keyword for Sentinel news scanning.
    哨兵新聞掃描的加權風險關鍵字。

    Attributes:
        keyword: The search keyword (e.g. 'SEC investigation')
        weight: Importance weight (0.0-1.0). Higher = more urgent.
        category: Risk category (legal/financial/operational/geopolitical/market/custom)
        hit_count: Number of times this keyword triggered an alert.
        last_hit_date: Last date this keyword triggered (for review/pruning).
        is_active: Whether this keyword is active for scanning.
        created_at: Creation timestamp.
    """
    keyword: str
    weight: float = 0.5
    category: RiskCategory = RiskCategory.CUSTOM
    hit_count: int = 0
    last_hit_date: Optional[str] = None
    is_active: bool = True
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    id: Optional[str] = None

    def score(self, text: str) -> float:
        """
        Return weighted score if keyword is found in text, else 0.
        計算此關鍵字在指定文字中的加權分數。
        """
        if not self.is_active:
            return 0.0
        if self.keyword.lower() in text.lower():
            return self.weight
        return 0.0
