"""
Smart Order Routing & Liquidity-Aware Execution Service (E1)
智能訂單路由與流動性感知分批執行服務
=============================================================================
Bridges high-level portfolio optimization signals (M1~M6) with real-world
execution venues to minimize market impact, control slippage, and prevent HFT
front-running.

Key Architecture:
1. ADV Constraint & Rollover Queue:
   - Caps single-session executable volume to a strict fraction of 20-day
     Average Daily Volume (ADV20), default <= 1.5%.
   - Excess quantities are diverted into an unfilled rollover queue.
2. Dynamic Routing Strategy (SOR):
   - DIRECT_LIMIT: Small orders (< $500 or < 0.1% ADV) execute as single limit/market order.
   - TWAP (Time-Weighted Average Price): Slices volume evenly across an execution window,
     injecting randomized time-step & quantity jitter (+/- 15%) to break HFT pattern recognition.
   - VWAP (Volume-Weighted Average Price): Uses an intraday bimodal U-Curve volume profile
     to align executions with liquidity peaks (market open and close).
3. Real-Time Slippage Monitoring & Circuit Breaker:
   - Continuously monitors child order fill slippage (in bps).
   - If fill slippage breaches max_slippage_bps (default 35 bps), the circuit breaker
     immediately trips, canceling all pending child slices to protect capital.
"""
from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from src.config.owner import resolve_user_id

logger = logging.getLogger(__name__)


class ExecutionStrategy(str, Enum):
    """Execution routing strategies."""
    DIRECT_LIMIT = "DIRECT_LIMIT"
    TWAP = "TWAP"
    VWAP = "VWAP"


class OrderAction(str, Enum):
    """Trading order direction."""
    BUY = "BUY"
    SELL = "SELL"


class ChildOrderStatus(str, Enum):
    """Status lifecycle of an execution child order."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


@dataclass
class ChildOrder:
    """Individual child order slice within a parent execution plan."""
    slice_index: int
    total_slices: int
    planned_delay_seconds: float
    target_quantity: float
    target_amount_usd: Optional[float] = None
    limit_price: Optional[float] = None
    status: ChildOrderStatus = ChildOrderStatus.PENDING
    filled_quantity: float = 0.0
    filled_price: Optional[float] = None
    executed_at: Optional[str] = None
    slippage_bps: Optional[float] = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "slice_index": self.slice_index,
            "total_slices": self.total_slices,
            "planned_delay_seconds": round(self.planned_delay_seconds, 1),
            "target_quantity": round(self.target_quantity, 4),
            "target_amount_usd": round(self.target_amount_usd, 2) if self.target_amount_usd is not None else None,
            "limit_price": round(self.limit_price, 4) if self.limit_price is not None else None,
            "status": self.status.value,
            "filled_quantity": round(self.filled_quantity, 4),
            "filled_price": round(self.filled_price, 4) if self.filled_price is not None else None,
            "executed_at": self.executed_at,
            "slippage_bps": round(self.slippage_bps, 2) if self.slippage_bps is not None else None,
        }


@dataclass
class SlicingPlan:
    """Comprehensive multi-slice execution plan generated by SOR."""
    symbol: str
    action: OrderAction
    strategy: ExecutionStrategy
    total_requested_quantity: float
    adv_20: float
    adv_limit_pct: float
    approved_quantity: float
    unfilled_rollover_quantity: float
    arrival_price: float
    execution_window_minutes: int
    num_slices: int
    child_orders: list[ChildOrder] = field(default_factory=list)
    status: str = "PLANNED"  # PLANNED, EXECUTING, COMPLETED, CIRCUIT_BREAKER_TRIGGERED
    circuit_breaker_triggered: bool = False
    circuit_breaker_reason: Optional[str] = None
    avg_executed_price: Optional[float] = None
    total_slippage_bps: Optional[float] = None
    implementation_shortfall_bps: Optional[float] = None
    execution_efficiency: float = 1.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "strategy": self.strategy.value,
            "total_requested_quantity": round(self.total_requested_quantity, 4),
            "adv_20": round(self.adv_20, 2),
            "adv_limit_pct": round(self.adv_limit_pct, 4),
            "approved_quantity": round(self.approved_quantity, 4),
            "unfilled_rollover_quantity": round(self.unfilled_rollover_quantity, 4),
            "arrival_price": round(self.arrival_price, 4),
            "execution_window_minutes": self.execution_window_minutes,
            "num_slices": self.num_slices,
            "child_orders": [child.to_dict() for child in self.child_orders],
            "status": self.status,
            "circuit_breaker_triggered": self.circuit_breaker_triggered,
            "circuit_breaker_reason": self.circuit_breaker_reason,
            "avg_executed_price": round(self.avg_executed_price, 4) if self.avg_executed_price is not None else None,
            "total_slippage_bps": round(self.total_slippage_bps, 2) if self.total_slippage_bps is not None else None,
            "implementation_shortfall_bps": round(self.implementation_shortfall_bps, 2) if self.implementation_shortfall_bps is not None else None,
            "execution_efficiency": round(self.execution_efficiency, 4),
        }


class SmartOrderRoutingService:
    """Smart Order Routing and Slicing Engine."""

    DEFAULT_ADV_MAX_PCT = 0.015               # 1.5% of ADV20
    DEFAULT_MAX_SLIPPAGE_BPS = 35.0           # 35 bps circuit breaker
    DEFAULT_EXECUTION_WINDOW_MINUTES = 30     # 30-minute slicing window
    DEFAULT_JITTER_PCT = 0.15                 # +/- 15% interval & size randomization
    SMALL_ORDER_VALUE_THRESHOLD = 500.0       # Orders < $500 direct route

    def __init__(self, user_id: str = "default_user", settings_repo: Any = None):
        self.user_id = resolve_user_id(user_id)
        self.settings_repo = settings_repo

    def _get_setting(self, key: str, default: Any, val_type: type = float) -> Any:
        """Helper to retrieve dynamic setting with fallback."""
        if not self.settings_repo:
            return default
        try:
            val = self.settings_repo.get(self.user_id, key)
            if val is None:
                return default
            if val_type is bool:
                return str(val).lower() in ("true", "1", "yes")
            return val_type(val)
        except Exception as e:
            logger.warning(f"Error loading setting '{key}' ({e}); using default {default}")
            return default

    @property
    def is_enabled(self) -> bool:
        return self._get_setting("sor_enabled", True, bool)

    @property
    def adv_max_pct(self) -> float:
        return float(self._get_setting("sor_adv_max_pct", self.DEFAULT_ADV_MAX_PCT, float))

    @property
    def max_slippage_bps(self) -> float:
        return float(self._get_setting("sor_max_slippage_bps", self.DEFAULT_MAX_SLIPPAGE_BPS, float))

    @property
    def default_execution_window_minutes(self) -> int:
        return int(self._get_setting("sor_default_execution_window_minutes", self.DEFAULT_EXECUTION_WINDOW_MINUTES, int))

    @property
    def twap_jitter_pct(self) -> float:
        return float(self._get_setting("sor_twap_jitter_pct", self.DEFAULT_JITTER_PCT, float))

    def generate_plan(
        self,
        symbol: str,
        action: str | OrderAction,
        requested_quantity: float,
        arrival_price: float,
        adv_20: float,
        execution_window_minutes: Optional[int] = None,
        force_strategy: Optional[ExecutionStrategy | str] = None,
        random_seed: Optional[int] = None,
        num_slices: Optional[int] = None,
    ) -> SlicingPlan:
        """
        Generate a liquidity-aware slicing plan with ADV constraint and routing strategy.
        """
        if isinstance(action, OrderAction):
            parsed_action = action
        else:
            parsed_action = OrderAction(str(action).upper())
        window_minutes = int(execution_window_minutes or self.default_execution_window_minutes)
        window_minutes = max(5, min(240, window_minutes))

        abs_quantity = abs(float(requested_quantity))
        adv = max(1.0, float(adv_20))
        price = max(0.0001, float(arrival_price))

        # 1. ADV Constraint Gating
        adv_limit = self.adv_max_pct
        max_allowed_shares = adv * adv_limit

        if abs_quantity > max_allowed_shares:
            approved_quantity = round(max_allowed_shares, 4)
            rollover_quantity = round(abs_quantity - approved_quantity, 4)
            logger.info(
                f"SOR ADV Constraint: {symbol} requested {abs_quantity:.4f} > limit "
                f"{max_allowed_shares:.4f} ({adv_limit * 100:.1f}% of ADV {adv:.0f}). "
                f"Approved: {approved_quantity:.4f}, Rollover: {rollover_quantity:.4f}"
            )
        else:
            approved_quantity = round(abs_quantity, 4)
            rollover_quantity = 0.0

        # Handle zero or micro approved quantity
        if approved_quantity <= 0.0:
            return SlicingPlan(
                symbol=symbol.upper(),
                action=parsed_action,
                strategy=ExecutionStrategy.DIRECT_LIMIT,
                total_requested_quantity=abs_quantity,
                adv_20=adv,
                adv_limit_pct=adv_limit,
                approved_quantity=0.0,
                unfilled_rollover_quantity=abs_quantity,
                arrival_price=price,
                execution_window_minutes=window_minutes,
                num_slices=0,
                child_orders=[],
                status="COMPLETED",
            )

        # 2. Strategy Routing Decision
        if not self.is_enabled:
            selected_strategy = ExecutionStrategy.DIRECT_LIMIT
        elif force_strategy is not None:
            if isinstance(force_strategy, ExecutionStrategy):
                selected_strategy = force_strategy
            else:
                selected_strategy = ExecutionStrategy(str(force_strategy).upper())
        else:
            est_order_value = approved_quantity * price
            # Small orders or negligible ADV fractions bypass slicing to reduce commission friction
            if est_order_value < self.SMALL_ORDER_VALUE_THRESHOLD or approved_quantity < (adv * 0.0005) or approved_quantity < 5.0:
                selected_strategy = ExecutionStrategy.DIRECT_LIMIT
            else:
                selected_strategy = ExecutionStrategy.TWAP

        # 3. Slice Count Determination
        if selected_strategy == ExecutionStrategy.DIRECT_LIMIT:
            slices_count = 1
        elif num_slices is not None:
            slices_count = max(2, min(24, int(num_slices)))
        else:
            # Slices scaled with window: roughly 1 slice per 3~5 minutes
            slices_count = max(3, min(12, int(window_minutes / 3)))

        rng = random.Random(random_seed) if random_seed is not None else random.Random()

        # 4. Generate Child Order Schedule
        child_orders: list[ChildOrder] = []
        jitter = self.twap_jitter_pct
        max_slippage = self.max_slippage_bps

        if selected_strategy == ExecutionStrategy.DIRECT_LIMIT:
            limit_p = price * (1.0 + (max_slippage / 10000.0) if parsed_action == OrderAction.BUY else 1.0 - (max_slippage / 10000.0))
            child_orders.append(
                ChildOrder(
                    slice_index=1,
                    total_slices=1,
                    planned_delay_seconds=0.0,
                    target_quantity=approved_quantity,
                    target_amount_usd=round(approved_quantity * price, 2),
                    limit_price=round(limit_p, 4),
                    status=ChildOrderStatus.PENDING,
                )
            )

        elif selected_strategy == ExecutionStrategy.TWAP:
            total_duration_sec = window_minutes * 60.0
            base_interval_sec = total_duration_sec / slices_count
            base_slice_shares = approved_quantity / slices_count

            # Generate randomized weights
            raw_weights: list[float] = []
            for _ in range(slices_count):
                pert = 1.0 + rng.uniform(-jitter, jitter)
                raw_weights.append(pert)
            weight_sum = sum(raw_weights)
            norm_weights = [w / weight_sum for w in raw_weights]

            # Compute allocated shares
            allocated_shares = [round(approved_quantity * w, 4) for w in norm_weights]
            # Ensure exact sum balance on final slice
            diff = round(approved_quantity - sum(allocated_shares), 4)
            allocated_shares[-1] = round(allocated_shares[-1] + diff, 4)

            # Generate cumulative delays with interval jitter
            delays: list[float] = [0.0]
            current_delay = 0.0
            for i in range(1, slices_count):
                interval = base_interval_sec * (1.0 + rng.uniform(-jitter, jitter))
                current_delay += interval
                delays.append(min(current_delay, total_duration_sec - 1.0))

            for idx in range(slices_count):
                limit_p = price * (1.0 + (max_slippage / 10000.0) if parsed_action == OrderAction.BUY else 1.0 - (max_slippage / 10000.0))
                q = allocated_shares[idx]
                child_orders.append(
                    ChildOrder(
                        slice_index=idx + 1,
                        total_slices=slices_count,
                        planned_delay_seconds=round(delays[idx], 1),
                        target_quantity=q,
                        target_amount_usd=round(q * price, 2),
                        limit_price=round(limit_p, 4),
                        status=ChildOrderStatus.PENDING,
                    )
                )

        elif selected_strategy == ExecutionStrategy.VWAP:
            # Bimodal U-Curve: higher volume near start (index 0) and close (index N-1)
            total_duration_sec = window_minutes * 60.0
            base_interval_sec = total_duration_sec / slices_count

            u_curve_weights: list[float] = []
            mid_point = (slices_count - 1) / 2.0 if slices_count > 1 else 1.0

            for idx in range(slices_count):
                if slices_count > 1:
                    norm_x = (idx - mid_point) / mid_point
                    # U-shape quadratic profile: weight is 1.0 at center, 2.5 at boundaries
                    w = 1.0 + 1.5 * (norm_x ** 2)
                else:
                    w = 1.0
                u_curve_weights.append(w)

            total_u_weight = sum(u_curve_weights)
            allocated_shares = [round(approved_quantity * (w / total_u_weight), 4) for w in u_curve_weights]
            diff = round(approved_quantity - sum(allocated_shares), 4)
            allocated_shares[-1] = round(allocated_shares[-1] + diff, 4)

            for idx in range(slices_count):
                delay = idx * base_interval_sec
                limit_p = price * (1.0 + (max_slippage / 10000.0) if parsed_action == OrderAction.BUY else 1.0 - (max_slippage / 10000.0))
                q = allocated_shares[idx]
                child_orders.append(
                    ChildOrder(
                        slice_index=idx + 1,
                        total_slices=slices_count,
                        planned_delay_seconds=round(delay, 1),
                        target_quantity=q,
                        target_amount_usd=round(q * price, 2),
                        limit_price=round(limit_p, 4),
                        status=ChildOrderStatus.PENDING,
                    )
                )

        return SlicingPlan(
            symbol=symbol.upper(),
            action=parsed_action,
            strategy=selected_strategy,
            total_requested_quantity=abs_quantity,
            adv_20=adv,
            adv_limit_pct=adv_limit,
            approved_quantity=approved_quantity,
            unfilled_rollover_quantity=rollover_quantity,
            arrival_price=price,
            execution_window_minutes=window_minutes,
            num_slices=slices_count,
            child_orders=child_orders,
            status="PLANNED",
        )

    def record_fill(
        self,
        plan: SlicingPlan,
        slice_index: int,
        filled_quantity: float,
        filled_price: float,
        timestamp_str: Optional[str] = None,
    ) -> SlicingPlan:
        """
        Record fill of a specific child order slice, evaluate slippage, and trip circuit breaker if breached.
        """
        if slice_index < 1 or slice_index > len(plan.child_orders):
            raise IndexError(f"Slice index {slice_index} out of range [1, {len(plan.child_orders)}]")

        child = plan.child_orders[slice_index - 1]
        child.filled_quantity = round(float(filled_quantity), 4)
        child.filled_price = round(float(filled_price), 4)
        child.executed_at = timestamp_str or "NOW"
        child.status = ChildOrderStatus.FILLED

        # 1. Child Slippage Calculation (bps)
        arrival_p = plan.arrival_price
        if plan.action == OrderAction.BUY:
            slippage_bps = ((child.filled_price - arrival_p) / arrival_p) * 10000.0
        else:
            slippage_bps = ((arrival_p - child.filled_price) / arrival_p) * 10000.0

        child.slippage_bps = round(slippage_bps, 2)

        # 2. Check Circuit Breaker
        max_allowed_slippage = self.max_slippage_bps
        if slippage_bps > max_allowed_slippage:
            plan.circuit_breaker_triggered = True
            plan.status = "CIRCUIT_BREAKER_TRIGGERED"
            plan.circuit_breaker_reason = (
                f"Child slice {slice_index} slippage {slippage_bps:.1f} bps breached "
                f"maximum tolerance threshold {max_allowed_slippage:.1f} bps"
            )
            logger.warning(f"🚨 SOR CIRCUIT BREAKER TRIPPED on {plan.symbol}: {plan.circuit_breaker_reason}")

            # Cancel remaining pending slices
            for remaining in plan.child_orders[slice_index:]:
                if remaining.status == ChildOrderStatus.PENDING:
                    remaining.status = ChildOrderStatus.CANCELLED
        else:
            plan.status = "EXECUTING"

        # 3. Update Plan-Level Cumulative Metrics
        filled_slices = [c for c in plan.child_orders if c.status == ChildOrderStatus.FILLED]
        total_filled_shares = sum(c.filled_quantity for c in filled_slices)

        if total_filled_shares > 0:
            avg_exec_price = sum(c.filled_quantity * (c.filled_price or 0.0) for c in filled_slices) / total_filled_shares
            plan.avg_executed_price = round(avg_exec_price, 4)

            if plan.action == OrderAction.BUY:
                cum_slippage_bps = ((avg_exec_price - arrival_p) / arrival_p) * 10000.0
            else:
                cum_slippage_bps = ((arrival_p - avg_exec_price) / arrival_p) * 10000.0

            plan.total_slippage_bps = round(cum_slippage_bps, 2)
            plan.implementation_shortfall_bps = round(cum_slippage_bps, 2)

            # Execution efficiency: 1.0 at 0 bps, degrades linearly with slippage (e.g. 0.5 at 50 bps)
            eff = max(0.0, min(1.0, 1.0 - (max(0.0, cum_slippage_bps) / 100.0)))
            plan.execution_efficiency = round(eff, 4)

        # 4. Check If All Slices Concluded
        all_done = all(
            c.status in (ChildOrderStatus.FILLED, ChildOrderStatus.CANCELLED, ChildOrderStatus.SKIPPED)
            for c in plan.child_orders
        )
        if all_done and not plan.circuit_breaker_triggered:
            plan.status = "COMPLETED"

        return plan

    def simulate_full_execution(
        self,
        plan: SlicingPlan,
        market_prices: Optional[list[float]] = None,
        price_drift_bps: float = 0.0,
        random_seed: Optional[int] = None,
    ) -> SlicingPlan:
        """
        Simulate fills across all child orders for backtesting and execution benchmarking.
        """
        rng = random.Random(random_seed) if random_seed is not None else random.Random()

        for idx, child in enumerate(plan.child_orders):
            if plan.circuit_breaker_triggered:
                break

            if market_prices and idx < len(market_prices):
                fill_p = market_prices[idx]
            else:
                # Synthetic market price around arrival with drift and noise
                noise_bps = rng.uniform(-10.0, 10.0)
                total_move_bps = (price_drift_bps * (idx + 1)) + noise_bps
                fill_p = plan.arrival_price * (1.0 + total_move_bps / 10000.0)

            self.record_fill(
                plan=plan,
                slice_index=child.slice_index,
                filled_quantity=child.target_quantity,
                filled_price=fill_p,
                timestamp_str=f"T+{child.planned_delay_seconds:.0f}s",
            )

        return plan
