"""final_schema_normalization_v8

Revision ID: f9861a2caa12
Revises: merge_all_heads_002
Create Date: 2026-05-01 00:07:48.053715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f9861a2caa12'
down_revision: Union[str, Sequence[str], None] = 'merge_all_heads_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_column(table: str, column: sa.Column, using: str = None) -> None:
    """
    Add `column`, or coerce an existing one to the target type.

    2026-08-02: every op.add_column in this revision was autogenerated against
    a database whose schema had drifted from the baseline chain, and each one
    targets a column 879480c2b31c already creates. op.add_column has no
    IF NOT EXISTS, so on a genuinely fresh `alembic upgrade head` all seventeen
    raised DuplicateColumn — which is why the chain had never run from base
    and why scripts/init_db.py:12-14 documents create_all-and-stamp as the
    workaround.

    The ALTER branch is not merely defensive. Six of these columns
    (cash_flows.user_id, daily_snapshots.time_horizon, recommendations.user_id,
    reports.user_id/report_type/title) are TEXT in the baseline but VARCHAR in
    the ORM, so coercing them is exactly the normalization this revision was
    named for. TEXT -> VARCHAR needs no USING clause. The other ten are already
    the target type, making the ALTER a no-op.

    2026-08-02：本 revision 的十七個 op.add_column 全都在加 baseline 已建好的
    欄位，而 add_column 沒有 IF NOT EXISTS，所以從空 DB 跑必炸 DuplicateColumn。
    ALTER 分支不只是防禦——其中六個欄位 baseline 是 TEXT 而 ORM 要 VARCHAR，
    收斂型別正是這支 migration 名稱所指的正規化。
    """
    inspector = sa.inspect(op.get_bind())
    existing = {c["name"] for c in inspector.get_columns(table)}
    if column.name not in existing:
        _ensure_column(table, column)
        return
    op.alter_column(
        table, column.name, type_=column.type,
        existing_nullable=True, postgresql_using=using,
    )


def _current_type(table: str, column: str) -> str:
    """Lowercased current type name of a column, or '' if it is absent."""
    inspector = sa.inspect(op.get_bind())
    for col in inspector.get_columns(table):
        if col["name"] == column:
            return str(col["type"]).lower()
    return ""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP VIEW IF EXISTS rebalance_health_summary CASCADE")

    # Fresh-install prerequisites. No migration in the chain creates these two
    # tables or this column, yet statements further down alter all three — the
    # production database only has them because it was built by
    # Base.metadata.create_all() and then stamped, never by running the chain.
    # Idempotent, so this is a no-op on any existing deployment.
    #
    # Deliberately omitted here: ix_portfolio_snapshots_user_id (line ~403),
    # ix_users_subscription_id and the users -> subscription_plans FK (~701-702).
    # This revision creates all three later and would fail on a duplicate.
    #
    # 鏈中沒有任何 migration 建立這兩張表與這個欄位，但後面卻要 alter 它們；
    # production 有它們是因為當初用 create_all + stamp 起的，從沒跑過整條鏈。
    # 全部冪等，對既有部署是 no-op。
    op.execute("""
        CREATE TABLE IF NOT EXISTS subscription_plans (
            id VARCHAR PRIMARY KEY,
            name VARCHAR NOT NULL UNIQUE,
            monthly_usd_limit NUMERIC(18, 2),
            allowed_tiers JSON,
            max_parallel_agents INTEGER,
            features JSON,
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS portfolio_snapshots (
            id SERIAL PRIMARY KEY,
            user_id VARCHAR,
            account_value NUMERIC(18, 2),
            cash NUMERIC(18, 2),
            invested NUMERIC(18, 2),
            portfolio_pl NUMERIC(18, 2),
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_id VARCHAR")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognitive_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('importance', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cog_mem_user_type', 'cognitive_memories', ['user_id', 'memory_type'], unique=False)
    op.create_index(op.f('ix_cognitive_memories_user_id'), 'cognitive_memories', ['user_id'], unique=False)
    op.create_table('prompt_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_cache_prompt_hash'), 'prompt_cache', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_prompt_cache_user_id'), 'prompt_cache', ['user_id'], unique=False)
    op.create_table('response_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_feedback_prompt_hash'), 'response_feedback', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_response_feedback_user_id'), 'response_feedback', ['user_id'], unique=False)
    op.create_table('web_push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscription_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('device_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_push_subscriptions_user_id'), 'web_push_subscriptions', ['user_id'], unique=False)
    op.execute('DROP TABLE IF EXISTS rebalance_events CASCADE')
    op.execute('DROP TABLE IF EXISTS daily_snapshots_backup CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_trading_exec_status')
    op.execute('DROP INDEX IF EXISTS idx_trading_exec_ticker')
    op.execute('DROP INDEX IF EXISTS idx_trading_exec_user_rebalance')
    op.execute('DROP TABLE IF EXISTS trading_execution_log CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_agent_analysis_agent_name')
    op.execute('DROP INDEX IF EXISTS idx_agent_analysis_user_rebalance')
    op.execute('DROP TABLE IF EXISTS agent_analysis_results CASCADE')
    op.execute('DROP TABLE IF EXISTS prompt_history CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_rebalance_eval_user_date')
    op.execute('DROP TABLE IF EXISTS rebalance_evaluation CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_pred_accuracy_agent')
    op.execute('DROP TABLE IF EXISTS agent_prediction_accuracy CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_sentinel_alerts_user_id')
    op.execute('DROP TABLE IF EXISTS sentinel_alerts CASCADE')
    op.execute('DROP TABLE IF EXISTS positions CASCADE')
    op.execute('DROP INDEX IF EXISTS idx_model_perf_user_date')
    op.execute('DROP TABLE IF EXISTS model_performance_metrics CASCADE')
    op.execute('DROP TABLE IF EXISTS sentinel_thresholds CASCADE')
    op.execute('DROP TABLE IF EXISTS schema_version CASCADE')
    op.alter_column('agent_feedback', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_feedback', 'agent_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_feedback', 'signal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agent_reviews', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_reviews', 'reviewer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_reviews', 'reviewee',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_reviews', 'context_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    _ensure_column('cash_flows', sa.Column('user_id', sa.String(), nullable=True))
    op.alter_column('cash_flows', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('cash_flows', 'date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=True,
               postgresql_using='date::date')
    op.alter_column('cash_flows', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               nullable=True)
    op.alter_column('cash_flows', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('cash_flows', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_cash_flows_user_id'), 'cash_flows', ['user_id'], unique=False)
    op.create_foreign_key(None, 'cash_flows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('channel_verifications', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('channel_verifications', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'channel_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('council_minutes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('council_minutes', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('council_minutes', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('council_minutes', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute("ALTER TABLE council_minutes ALTER COLUMN embedding DROP DEFAULT")
    op.alter_column('council_minutes', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"),
               postgresql_using='embedding::text::vector(1536)')
    op.execute('DROP INDEX IF EXISTS idx_council_minutes_created_at')
    op.execute('DROP INDEX IF EXISTS idx_council_minutes_session_id')
    op.execute('DROP INDEX IF EXISTS idx_council_minutes_user_id')
    op.create_index(op.f('ix_council_minutes_session_id'), 'council_minutes', ['session_id'], unique=False)
    op.create_index(op.f('ix_council_minutes_user_id'), 'council_minutes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'council_minutes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE council_minutes DROP COLUMN IF EXISTS updated_at")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    _ensure_column('daily_snapshots', sa.Column('total_tnv', sa.Numeric(precision=18, scale=8), nullable=True))
    _ensure_column('daily_snapshots', sa.Column('leverage_ratio', sa.Numeric(precision=18, scale=8), nullable=True))
    _ensure_column('daily_snapshots', sa.Column('conviction_level', sa.Numeric(precision=18, scale=8), nullable=True))
    _ensure_column('daily_snapshots', sa.Column('time_horizon', sa.String(), nullable=True))
    op.alter_column('daily_snapshots', 'date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='date::date')
    op.alter_column('daily_snapshots', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'90693c07-6177-42df-97d9-915f3ce7c573'::text"))
    op.alter_column('daily_snapshots', 'account_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('daily_snapshots', 'total_nlv',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'cash_balance',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'invested_capital',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'pnl',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS idx_daily_snapshots_user_date')
    op.execute('DROP INDEX IF EXISTS idx_daily_snapshots_user_id')
    op.create_foreign_key(None, 'daily_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('event_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_logs', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('event_logs', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_logs', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('event_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('investment_skills', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'timeframe',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('investment_skills', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'article'::text"))
    op.alter_column('investment_skills', 'source_highlight_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'job_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('job_telemetry', 'stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_telemetry', 'stage_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_telemetry', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'error_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.execute('DROP INDEX IF EXISTS idx_job_telemetry_completed_at')
    op.execute('DROP INDEX IF EXISTS idx_job_telemetry_job_stage')
    op.execute('DROP INDEX IF EXISTS idx_job_telemetry_stage_name')
    op.create_index(op.f('ix_job_telemetry_job_id'), 'job_telemetry', ['job_id'], unique=False)
    op.execute("ALTER TABLE job_telemetry DROP CONSTRAINT IF EXISTS job_telemetry_job_id_fkey")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    op.create_foreign_key(None, 'job_telemetry', 'report_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('llm_usage_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.alter_column('llm_usage_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('llm_usage_logs', 'agent_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('llm_usage_logs', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('llm_usage_logs', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('llm_usage_logs', 'tier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('llm_usage_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_llm_usage_logs_agent_name'), 'llm_usage_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_llm_usage_logs_user_id'), 'llm_usage_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'llm_usage_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('memory_embeddings', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('memory_embeddings', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('memory_embeddings', 'embedding_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.create_index(op.f('ix_memory_embeddings_user_id'), 'memory_embeddings', ['user_id'], unique=False)
    op.alter_column('portfolio_snapshots', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('portfolio_snapshots', 'account_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'cash',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'invested',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'portfolio_pl',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.alter_column('position_lots', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.alter_column('position_lots', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('position_lots', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('position_lots', 'open_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('position_lots', 'close_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('position_lots', 'source_tx_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    _ensure_column('recommendations', sa.Column('user_id', sa.String(), nullable=False))
    _ensure_column('recommendations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('recommendations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('recommendations', 'date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               postgresql_using='date::timestamp with time zone')
    op.alter_column('recommendations', 'agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('recommendations', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('recommendations', 'signal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('recommendations', 'price_at_signal',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE recommendations DROP COLUMN IF EXISTS outcome_score")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    op.alter_column('report_jobs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('report_jobs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('report_jobs', 'report_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('report_jobs', 'scheduled_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('report_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('report_jobs', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('report_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_jobs', 'report_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('report_jobs', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('report_jobs', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS idx_report_jobs_created_at')
    op.execute('DROP INDEX IF EXISTS idx_report_jobs_priority')
    op.execute('DROP INDEX IF EXISTS idx_report_jobs_scheduled_date')
    op.execute('DROP INDEX IF EXISTS idx_report_jobs_user_status')
    op.create_index(op.f('ix_report_jobs_user_id'), 'report_jobs', ['user_id'], unique=False)
    op.execute("ALTER TABLE report_jobs DROP CONSTRAINT IF EXISTS report_jobs_report_id_fkey")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    op.create_foreign_key(None, 'report_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _ensure_column('reports', sa.Column('user_id', sa.String(), nullable=False))
    _ensure_column('reports', sa.Column('report_type', sa.String(), nullable=False))
    _ensure_column('reports', sa.Column('title', sa.String(), nullable=False))
    _ensure_column('reports', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    _ensure_column('reports', sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    _ensure_column('reports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('reports', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reports', 'job_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'generation_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reports', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS idx_reports_generation_model')
    op.execute('DROP INDEX IF EXISTS idx_reports_job_id')
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.execute("ALTER TABLE reports DROP CONSTRAINT IF EXISTS fk_reports_job_id")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    op.create_foreign_key(None, 'reports', 'report_jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE reports DROP COLUMN IF EXISTS date")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    op.alter_column('risk_keywords', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('risk_keywords', 'keyword',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('risk_keywords', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'custom'::text"))
    op.alter_column('risk_keywords', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'seed'::text"))
    op.execute("ALTER TABLE risk_keywords DROP CONSTRAINT IF EXISTS risk_keywords_keyword_key")  # IF EXISTS: absent on a fresh chain, present on the drifted DB this was autogenerated against.
    _ensure_column('scheduler_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('scheduler_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduler_logs', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='timestamp::timestamp with time zone')
    op.alter_column('scheduler_logs', 'job_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('scheduler_logs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('settings', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # The USING clause applies the regex operator `~` to `value`, which only
    # works if the column is TEXT. On a fresh chain it is not: the baseline
    # creates `value JSONB` (879480c2b31c:81), so this raised UndefinedFunction.
    # Skip when the column is already a json type — there is nothing to coerce.
    # USING 子句對 value 用了文字正規表示式運算子，只有 TEXT 欄位適用；但從空鏈
    # 跑時 baseline 建的就是 JSONB，會直接炸。已是 json 類型就不需要轉換。
    if 'json' not in _current_type('settings', 'value'):
        op.alter_column('settings', 'value',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN value ~ '^\\s*[{\\[]' THEN value::json ELSE to_json(value) END")
    op.create_foreign_key(None, 'settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('skill_learning_config', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    _ensure_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    _ensure_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('transactions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'trade_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='trade_date::date')
    op.alter_column('transactions', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('transactions', 'fees',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('transactions', 'source_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'entry_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'trade'::text"))
    # Same TEXT-only USING clause as settings.value above; the baseline already
    # creates raw_data as JSONB. / 與上面 settings.value 同樣的問題。
    if 'json' not in _current_type('transactions', 'raw_data'):
        op.alter_column('transactions', 'raw_data',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN raw_data ~ '^\\s*[{\\[]' THEN raw_data::jsonb ELSE to_jsonb(raw_data) END")
    op.execute('DROP INDEX IF EXISTS idx_transactions_user_date')
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    op.create_index(op.f('ix_transactions_trade_date'), 'transactions', ['trade_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_identities', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_identities', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_identities', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_identities', 'identifier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.execute('DROP INDEX IF EXISTS idx_user_identities_user_id')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'subscription_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute('DROP INDEX IF EXISTS idx_users_email')
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'users', 'subscription_plans', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_users_subscription_id')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'subscription_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.alter_column('user_identities', 'identifier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_identities', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_identities', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_identities', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_transactions_user_id')
    op.execute('DROP INDEX IF EXISTS ix_transactions_trade_date')
    op.execute('DROP INDEX IF EXISTS ix_transactions_ticker')
    op.create_index(op.f('idx_transactions_user_date'), 'transactions', ['user_id', sa.literal_column('trade_date DESC')], unique=False)
    op.alter_column('transactions', 'raw_data',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'entry_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'trade'::text"))
    op.alter_column('transactions', 'source_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'::text"))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('transactions', 'fees',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('transactions', 'price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('transactions', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'trade_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.alter_column('subscription_plans', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('skill_learning_config', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.alter_column('settings', 'value',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settings', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('settings', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('scheduler_logs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('scheduler_logs', 'job_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('scheduler_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scheduler_logs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('scheduler_logs', 'created_at')
    op.create_unique_constraint(op.f('risk_keywords_keyword_key'), 'risk_keywords', ['keyword'])
    op.alter_column('risk_keywords', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'seed'::text"))
    op.alter_column('risk_keywords', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'custom'::text"))
    op.alter_column('risk_keywords', 'keyword',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('risk_keywords', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('reports', sa.Column('date', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reports_job_id'), 'reports', 'report_jobs', ['job_id'], ['id'])
    op.execute('DROP INDEX IF EXISTS ix_reports_user_id')
    op.execute('DROP INDEX IF EXISTS ix_reports_job_id')
    op.create_index(op.f('idx_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_index(op.f('idx_reports_generation_model'), 'reports', ['generation_model'], unique=False)
    op.alter_column('reports', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('reports', 'generation_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'job_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('reports', 'created_at')
    op.drop_column('reports', 'metadata')
    op.drop_column('reports', 'embedding')
    op.drop_column('reports', 'title')
    op.drop_column('reports', 'report_type')
    op.drop_column('reports', 'user_id')
    op.drop_constraint(None, 'report_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('report_jobs_report_id_fkey'), 'report_jobs', 'reports', ['report_id'], ['id'])
    op.execute('DROP INDEX IF EXISTS ix_report_jobs_user_id')
    op.create_index(op.f('idx_report_jobs_user_status'), 'report_jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_report_jobs_scheduled_date'), 'report_jobs', ['scheduled_date'], unique=False)
    op.create_index(op.f('idx_report_jobs_priority'), 'report_jobs', ['priority', 'created_at'], unique=False)
    op.create_index(op.f('idx_report_jobs_created_at'), 'report_jobs', ['created_at'], unique=False)
    op.alter_column('report_jobs', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('report_jobs', 'model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('report_jobs', 'report_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('report_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_jobs', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('report_jobs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('report_jobs', 'scheduled_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('report_jobs', 'report_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_jobs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('report_jobs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('recommendations', sa.Column('outcome_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_recommendations_user_id')
    op.alter_column('recommendations', 'price_at_signal',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recommendations', 'signal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('recommendations', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('recommendations', 'agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('recommendations', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('recommendations', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('recommendations', 'created_at')
    op.drop_column('recommendations', 'user_id')
    op.alter_column('position_lots', 'source_tx_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('position_lots', 'close_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('position_lots', 'open_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('position_lots', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('position_lots', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('position_lots', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.execute('DROP INDEX IF EXISTS ix_portfolio_snapshots_user_id')
    op.alter_column('portfolio_snapshots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_snapshots', 'portfolio_pl',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'invested',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'cash',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'account_value',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshots', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.execute('DROP INDEX IF EXISTS ix_memory_embeddings_user_id')
    op.alter_column('memory_embeddings', 'embedding_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.alter_column('memory_embeddings', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memory_embeddings', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'llm_usage_logs', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_llm_usage_logs_user_id')
    op.execute('DROP INDEX IF EXISTS ix_llm_usage_logs_agent_name')
    op.alter_column('llm_usage_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('llm_usage_logs', 'tier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('llm_usage_logs', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('llm_usage_logs', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('llm_usage_logs', 'agent_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('llm_usage_logs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('llm_usage_logs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())::text'))
    op.drop_constraint(None, 'job_telemetry', type_='foreignkey')
    op.create_foreign_key(op.f('job_telemetry_job_id_fkey'), 'job_telemetry', 'report_jobs', ['job_id'], ['id'])
    op.execute('DROP INDEX IF EXISTS ix_job_telemetry_job_id')
    op.create_index(op.f('idx_job_telemetry_stage_name'), 'job_telemetry', ['stage_name'], unique=False)
    op.create_index(op.f('idx_job_telemetry_job_stage'), 'job_telemetry', ['job_id', 'stage'], unique=False)
    op.create_index(op.f('idx_job_telemetry_completed_at'), 'job_telemetry', ['completed_at'], unique=False)
    op.alter_column('job_telemetry', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_telemetry', 'error_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_telemetry', 'stage_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_telemetry', 'stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_telemetry', 'job_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'source_highlight_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investment_skills', 'source_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'article'::text"))
    op.alter_column('investment_skills', 'timeframe',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investment_skills', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investment_skills', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('event_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('event_logs', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('event_logs', 'severity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_logs', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('event_logs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_logs', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'daily_snapshots', type_='foreignkey')
    op.create_index(op.f('idx_daily_snapshots_user_id'), 'daily_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('idx_daily_snapshots_user_date'), 'daily_snapshots', ['user_id', 'date'], unique=False)
    op.alter_column('daily_snapshots', 'pnl',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'invested_capital',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'cash_balance',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'total_nlv',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_snapshots', 'account_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('daily_snapshots', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'90693c07-6177-42df-97d9-915f3ce7c573'::text"))
    op.alter_column('daily_snapshots', 'date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('daily_snapshots', 'time_horizon')
    op.drop_column('daily_snapshots', 'conviction_level')
    op.drop_column('daily_snapshots', 'leverage_ratio')
    op.drop_column('daily_snapshots', 'total_tnv')
    op.add_column('council_minutes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'council_minutes', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_council_minutes_user_id')
    op.execute('DROP INDEX IF EXISTS ix_council_minutes_session_id')
    op.create_index(op.f('idx_council_minutes_user_id'), 'council_minutes', ['user_id'], unique=False)
    op.create_index(op.f('idx_council_minutes_session_id'), 'council_minutes', ['session_id'], unique=False)
    op.create_index(op.f('idx_council_minutes_created_at'), 'council_minutes', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('council_minutes', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('council_minutes', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('council_minutes', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('council_minutes', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('council_minutes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('channel_verifications', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('channel_verifications', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'channel_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'channel',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('channel_verifications', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'cash_flows', type_='foreignkey')
    op.execute('DROP INDEX IF EXISTS ix_cash_flows_user_id')
    op.alter_column('cash_flows', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cash_flows', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('cash_flows', 'amount',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('cash_flows', 'date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('cash_flows', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('cash_flows', 'user_id')
    op.alter_column('agent_reviews', 'context_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agent_reviews', 'reviewee',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agent_reviews', 'reviewer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agent_reviews', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agent_feedback', 'signal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agent_feedback', 'agent_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agent_feedback', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('schema_version',
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_version_pkey'))
    )
    op.create_table('sentinel_thresholds',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_optimized_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roi_hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentinel_thresholds_pkey')),
    sa.UniqueConstraint('key', name=op.f('sentinel_thresholds_key_key'))
    )
    op.create_table('model_performance_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('analysis_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_token_per_call', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_cost_usd', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('model_performance_metrics_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('model_performance_metrics_pkey'))
    )
    op.create_index(op.f('idx_model_perf_user_date'), 'model_performance_metrics', ['user_id', sa.literal_column('analysis_date DESC')], unique=False)
    op.create_table('positions',
    sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('avg_cost', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('market_value', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('unrealized_pl', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey')),
    sa.UniqueConstraint('user_id', 'ticker', name=op.f('positions_unique_user_ticker'))
    )
    op.create_table('sentinel_alerts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentinel_alerts_pkey'))
    )
    op.create_index(op.f('idx_sentinel_alerts_user_id'), 'sentinel_alerts', ['user_id'], unique=False)
    op.create_table('agent_prediction_accuracy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prediction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rebalance_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prediction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prediction', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('prediction_target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('predicted_value', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('actual_value', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('accuracy_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('error_pct', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True),
    sa.Column('time_horizon_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_prediction_accuracy_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_prediction_accuracy_pkey')),
    sa.UniqueConstraint('prediction_id', name=op.f('agent_prediction_accuracy_prediction_id_key'))
    )
    op.create_index(op.f('idx_pred_accuracy_agent'), 'agent_prediction_accuracy', ['agent_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('rebalance_evaluation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rebalance_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('cost_overrun_pct', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('portfolio_efficiency', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('pre_rebalance_return', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True),
    sa.Column('post_rebalance_return', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True),
    sa.Column('alpha_generated', sa.NUMERIC(precision=7, scale=4), autoincrement=False, nullable=True),
    sa.Column('strategy_employed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('macro_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cio_recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evaluator_insights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rebalance_evaluation_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rebalance_evaluation_pkey')),
    sa.UniqueConstraint('rebalance_id', name=op.f('rebalance_evaluation_rebalance_id_key'))
    )
    op.create_index(op.f('idx_rebalance_eval_user_date'), 'rebalance_evaluation', ['user_id', sa.literal_column('start_date DESC')], unique=False)
    op.create_table('prompt_history',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diff_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_history_pkey'))
    )
    op.create_table('agent_analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rebalance_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('openrouter_model_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('analysis_input', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis_output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_analysis_results_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_analysis_results_pkey'))
    )
    op.create_index(op.f('idx_agent_analysis_user_rebalance'), 'agent_analysis_results', ['user_id', 'rebalance_id'], unique=False)
    op.create_index(op.f('idx_agent_analysis_agent_name'), 'agent_analysis_results', ['agent_name'], unique=False)
    op.create_table('trading_execution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rebalance_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('target_shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filled_shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('filled_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('commission', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('slippage_bps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('broker_order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('pnl_pct', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('broker_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trading_execution_log_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_execution_log_pkey')),
    sa.UniqueConstraint('trade_id', name=op.f('trading_execution_log_trade_id_key'))
    )
    op.create_index(op.f('idx_trading_exec_user_rebalance'), 'trading_execution_log', ['user_id', 'rebalance_id'], unique=False)
    op.create_index(op.f('idx_trading_exec_ticker'), 'trading_execution_log', ['ticker'], unique=False)
    op.create_index(op.f('idx_trading_exec_status'), 'trading_execution_log', ['status'], unique=False)
    op.create_table('daily_snapshots_backup',
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_nlv', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cash_balance', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('invested_capital', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.create_table('rebalance_events',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('council_decision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actions_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('actions_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rebalance_events_pkey'))
    )
    op.execute('DROP INDEX IF EXISTS ix_web_push_subscriptions_user_id')
    op.execute('DROP TABLE IF EXISTS web_push_subscriptions CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_response_feedback_user_id')
    op.execute('DROP INDEX IF EXISTS ix_response_feedback_prompt_hash')
    op.execute('DROP TABLE IF EXISTS response_feedback CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_prompt_cache_user_id')
    op.execute('DROP INDEX IF EXISTS ix_prompt_cache_prompt_hash')
    op.execute('DROP TABLE IF EXISTS prompt_cache CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_cognitive_memories_user_id')
    op.execute('DROP INDEX IF EXISTS idx_cog_mem_user_type')
    op.execute('DROP TABLE IF EXISTS cognitive_memories CASCADE')
    # ### end Alembic commands ###
