import logging
import json
import uuid
import typing
from typing import List, Dict, Tuple, Any, Optional, Callable, Dict, List, Tuple, Any, Optional, Callable

from src.agents.base_agent import BaseAgent
from src.repositories.settings_repository import AlchemySettingsRepository

logger = logging.getLogger(__name__)

class CodeGenerator:
    """Mock/Stub for Code Generator."""
    def generate(self, prompt: str) -> str:
        # In a real system, this would call an LLM with strict code formatting
        # 實際系統中將調用 LLM 生成精確的量化交易代碼
        func_name = f"alpha_feature_v{uuid.uuid4().hex[:6]}"
        return f"def {func_name}(data):\n    # Generated by AlphaEngineer\n    return data.get('close', 0) * 1.05\n"

class BacktestRunner:
    """Mock/Stub for Backtest Runner."""
    def run(self, code: str, ticker: str) -> Dict[str, float]:
        # Mocking backtest performance using random simulation
        # 模擬回測效能
        import random
        return {
            "sharpe_ratio": round(random.uniform(0.5, 2.5), 2),
            "max_drawdown": round(random.uniform(-0.3, -0.05), 2),
            "win_rate": round(random.uniform(0.4, 0.7), 2)
        }

class SystemEngineerAgent(BaseAgent):
    """
    Milestone 5.3: Engineer Swarm & Alpha-Seeking
    Autonomous code generation and backtesting for alpha discovery.
    """
    def __init__(self, user_id: str, **kwargs):
        # We use a completely new class name or alias to avoid conflict with `engineer.py`
        # Using suffix `Agent` but distinct file name `system_engineer_agent.py`
        super().__init__(
            name="AlphaEngineer", 
            prompt_path="prompts/common/default_system.j2",
            tier="adv",
            user_id=user_id,
            **kwargs
        )
        self.code_gen = CodeGenerator()
        self.backtester = BacktestRunner()
        self.settings = AlchemySettingsRepository()

    def run(self, context: Any) -> str:
        """
        Runs the alpha-seeking genetic algorithm workflow.
        """
        ticker = context.get("ticker", "SPY")
        generations = context.get("generations", 3)
        population_size = context.get("population_size", 3)
        
        logger.info(f"AlphaEngineer: Starting Genetic Algorithm for {ticker} (Gens: {generations}, Pop: {population_size})")
        
        best_code = ""
        best_score = -999.0
        best_metrics = {}
        
        for g in range(generations):
            logger.info(f"--- Generation {g+1} ---")
            for p in range(population_size):
                # 1. Generate Variant
                instruction = f"Create a trading alpha factor for {ticker} using price momentum and volume."
                if best_code:
                    instruction += f" Mutate this baseline code to improve Sharpe:\n{best_code}"
                
                new_code = self.code_gen.generate(instruction)
                
                # 2. Backtest
                metrics = self.backtester.run(new_code, ticker)
                score = metrics["sharpe_ratio"]
                
                logger.info(f"Variant {p+1} Score: {score} (Sharpe: {metrics['sharpe_ratio']}, WR: {metrics['win_rate']})")
                
                # 3. Selection
                if score > best_score:
                    best_score = score
                    best_code = new_code
                    best_metrics = metrics
                    
        # 4. Save best Alpha to Repository (or disk)
        alpha_id = f"alpha_{ticker.lower()}_{uuid.uuid4().hex[:4]}"
        self.settings.set(self.user_id, alpha_id, json.dumps({
            "code": best_code,
            "metrics": best_metrics
        }))
        
        report = (
            f"### 🧬 Alpha Discovery Complete ({ticker})\n"
            f"- **Best Model ID**: `{alpha_id}`\n"
            f"- **Sharpe Ratio**: {best_score}\n"
            f"- **Win Rate**: {best_metrics.get('win_rate', 0) * 100}%\n"
            f"- **Max Drawdown**: {best_metrics.get('max_drawdown', 0) * 100}%\n\n"
            f"**Code Snippet**:\n```python\n{best_code}```"
        )
        return report
