import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import markdown
from dotenv import load_dotenv
from src.utils.logger import setup_logger

# Load environment variables from .env file
load_dotenv()

class EmailNotifier:
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.sender_email = os.getenv("SMTP_USER")
        self.sender_password = os.getenv("SMTP_PASSWORD")
        self.recipient_email = os.getenv("EMAIL_RECIPIENT")
        self.logger = setup_logger("EmailNotifier")
        self.blocked_domains = ["example.com"]
        self.blocked_emails = ["your_email@gmail.com", "admin@example.com"]

    def _get_css(self):
        """Return professional CSS styles for the email."""
        return """
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f9f9f9; padding: 20px; }
            .container { max-width: 800px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 0; }
            h2 { color: #34495e; margin-top: 25px; border-left: 4px solid #3498db; padding-left: 10px; }
            h3 { color: #7f8c8d; margin-top: 20px; }
            p { margin-bottom: 15px; }
            strong { color: #2c3e50; font-weight: 600; }
            ul, ol { margin-bottom: 15px; padding-left: 20px; }
            li { margin-bottom: 5px; }
            blockquote { border-left: 4px solid #bdc3c7; margin: 0; padding-left: 15px; color: #7f8c8d; font-style: italic; }
            code { background-color: #f8f9fa; padding: 2px 4px; border-radius: 4px; font-family: Monaco, Consolas, monospace; font-size: 0.9em; color: #e74c3c; }
            pre { background-color: #2c3e50; color: #ecf0f1; padding: 15px; border-radius: 5px; overflow-x: auto; }
            pre code { background-color: transparent; color: #ecf0f1; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { padding: 12px; border: 1px solid #e0e0e0; text-align: left; }
            th { background-color: #f4f6f7; font-weight: 600; color: #2c3e50; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { margin-top: 30px; border-top: 1px solid #e0e0e0; padding-top: 20px; font-size: 0.85em; color: #95a5a6; text-align: center; }
            .alert { padding: 15px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }
            .alert-info { color: #31708f; background-color: #d9edf7; border-color: #bce8f1; }
            .alert-warning { color: #8a6d3b; background-color: #fcf8e3; border-color: #faebcc; }
        </style>
        """

    def _structure_html(self, subject, html_content):
        """Wrap content in a proper HTML Email structure."""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{subject}</title>
            {self._get_css()}
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>AI Investment Advisor</h1>
                </div>
                <div class="content">
                    {html_content}
                </div>
                <div class="footer">
                    <p>Generated by AI Investment Advisor Agent Swarm. Not financial advice.</p>
                </div>
            </div>
        </body>
        </html>
        """

    def send_report(self, subject, content, to_email=None):
        if not self.sender_email or not self.sender_password:
            self.logger.warning("Email credentials not set. Skipping email notification.")
            return False

        recipient = to_email if to_email else self.recipient_email
        if not recipient:
             self.logger.warning("No recipient specified. Skipping email.")
             return False

        # Validate recipient
        if recipient in self.blocked_emails:
            self.logger.warning(f"Recipient {recipient} is in blocklist. Skipping email.")
            return False
            
        domain = recipient.split('@')[-1] if '@' in recipient else ''
        if domain in self.blocked_domains:
             self.logger.warning(f"Recipient domain {domain} is in blocklist. Skipping email.")
             return False

        msg = MIMEMultipart('alternative')
        msg['From'] = self.sender_email
        msg['To'] = recipient
        msg['Subject'] = subject

        # 1. Attach Plain Text Version (Backup)
        part1 = MIMEText(content, 'plain', 'utf-8')
        msg.attach(part1)

        # 2. Attach HTML Version (Beautified)
        # Convert Markdown to HTML
        try:
            html_body = markdown.markdown(content, extensions=['tables', 'fenced_code'])
            full_html = self._structure_html(subject, html_body)
            part2 = MIMEText(full_html, 'html', 'utf-8')
            msg.attach(part2)
        except Exception as e:
            self.logger.error(f"Markdown conversion failed: {e}. Sending plain text only.")
            # Already attached plain text, so just proceed

        try:
            self.logger.info(f"Connecting to SMTP server: {self.smtp_server}:{self.smtp_port}...")
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()

            self.logger.info(f"Logging in as {self.sender_email}...")
            server.login(self.sender_email, self.sender_password)

            self.logger.info(f"Sending email to {recipient}...")
            server.send_message(msg)
            server.quit()

            self.logger.info("Email sent successfully.")
            return True
        except Exception as e:
            self.logger.error(f"Failed to send email: {e}", exc_info=True)
            return False

if __name__ == "__main__":
    # Test
    notifier = EmailNotifier()
    notifier.send_report("Test Report", "# Hello\nThis is a test.")
